In [ ]:
##Creating Matrix

In [68]:
import numpy as np

In [69]:
M1 = np.array([[3,4,5],[7,1,9]])

In [70]:
M1

array([[3, 4, 5],
       [7, 1, 9]])

In [73]:
M1.shape

(2, 3)

In [72]:
M2 = np.array([[3,4],[7,9],[6,2],[8,5]])

In [75]:
M2

array([[3, 4],
       [7, 9],
       [6, 2],
       [8, 5]])

In [74]:
M2.shape

(4, 2)

In [ ]:
Types of Matrices

In [ ]:
#Row matrix

In [83]:
R = np.array([[4,7,4,2,7,8]])

In [84]:
R

array([[4, 7, 4, 2, 7, 8]])

In [85]:
R.shape

(1, 6)

In [86]:
type(R)

numpy.ndarray

In [88]:
R.reshape(3,2)

array([[4, 7],
       [4, 2],
       [7, 8]])

In [67]:
c = np.array([[4],[7],[4],[2],[7],[8]])

In [ ]:
#Column matrix

In [89]:
C = np.array([[4],[7],[4],[2],[7],[8]])

In [90]:
C

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

In [91]:
C.shape

(6, 1)

In [92]:
C.reshape(3,2)

array([[4, 7],
       [4, 2],
       [7, 8]])

In [93]:
C.reshape(6,1)

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

In [94]:
C.reshape(1,6)

array([[4, 7, 4, 2, 7, 8]])

In [95]:
C.T

array([[4, 7, 4, 2, 7, 8]])

In [96]:
R.T

array([[4],
       [7],
       [4],
       [2],
       [7],
       [8]])

In [ ]:
##Square matrix

In [98]:
M1=np.array([[5,6,7],[2,8,9],[2,1,4]])

In [99]:
M1

array([[5, 6, 7],
       [2, 8, 9],
       [2, 1, 4]])

In [100]:
def isSquareMatrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False

In [101]:
isSquareMatrix(M1)

True

In [102]:
isSquareMatrix(R)

False

In [103]:
M2 = np.array([[5,6,7],[2,8,9]])

In [104]:
M2

array([[5, 6, 7],
       [2, 8, 9]])

In [105]:
def isRectangularMatrix(M):
    if M.shape[0] == M.shape[1]:
        return False
    else:
        return True

In [106]:
isRectangularMatrix(M1)

False

In [107]:
isRectangularMatrix(M2)

True

In [108]:
M1

array([[5, 6, 7],
       [2, 8, 9],
       [2, 1, 4]])

In [16]:
M1.shape

(3, 3)

In [17]:
M1[0]

array([5, 6, 7])

In [126]:
M3=np.zeros([4,4], dtype=np.int8)

In [127]:
M3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [128]:
M3 = M3 + 4

In [129]:
M3

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

In [ ]:
##Diagonal matrix

In [130]:
D = np.array([[1,0,0],[0,8,0],[0,0,9]])

In [131]:
D

array([[1, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])

In [132]:
D=np.zeros([4,4], dtype=np.int8)

In [133]:
D

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [134]:
for i in range(4):
    D[i][i] = 6

In [135]:
D

array([[6, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 6]], dtype=int8)

In [151]:
for i in range(D.shape[0]):
    for j in range(D.shape[1]):
        print(D[i][j])

6
0
0
0
0
6
0
0
0
0
6
0
0
0
0
6


In [148]:
def isDiagonalMatrix(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i != j and M[i][j] != 0:
                return False
    return True

In [149]:
isDiagonalMatrix(D)

True

In [150]:
isDiagonalMatrix(M1)

False

In [ ]:
## Identity matrix

In [39]:
I = np.zeros([4,4], dtype=np.int8)

In [40]:
I

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [152]:
for i in range(4):
    I[i][i]= 1

In [153]:
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [44]:
I.diagonal()

array([1, 1, 1, 1], dtype=int8)

In [154]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

In [ ]:
##Symmetric matrix

In [46]:
S1 = np.array([[2,3,6],[3,4,5],[6,5,9]])

In [47]:
S1

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [48]:
S1.T

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [49]:
S1 == S1.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [50]:
(S1 == S1.T).sum()

9

In [52]:
S1.size

9

In [53]:
def isSymmetricMatrix(M):
    if (M==M.T).sum() == M.size:
        return True
    else:
        return False

In [54]:
isSymmetricMatrix(S1)

True

In [55]:
isSymmetricMatrix(M1)

False

In [ ]:
Skew-symmetric matrix

In [56]:
S2 = np.array([[0,3],[-3,0]])

In [57]:
S2

array([[ 0,  3],
       [-3,  0]])

In [58]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

In [59]:
-S2

array([[ 0, -3],
       [ 3,  0]])

In [ ]:
##Eigenvector and Eigenvalues

In [60]:
A= np.array([[-6,3],[4,5]])

In [61]:
A

array([[-6,  3],
       [ 4,  5]])

In [62]:
#calculate eigenvalue and eigenvector
eval, evect = np.linalg.eig(A)

In [63]:
evect

array([[-0.9486833 , -0.24253563],
       [ 0.31622777, -0.9701425 ]])

In [64]:
eval

array([-7.,  6.])

In [65]:
A @ evect

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [66]:
eval * evect

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])